### ISSUE TITLE
Comma seperated phrases / case-insensitive

### ISSUE THREAD

**Issue by opiekuni** [Pixabay/jQuery-autoComplete#11]
First of all, thank you so much for delivering such a tremendous tiny script :)
I haven't found anywhere a possibility where i can contact you, so i am doing it here to ask 2 Questions and hope you don't mind it. 

We are using your script for geo data that is separated by comma for example: State, County, City
1) How can we manage it that we can type in the State and City and both will be recognized? In other words every phrase separated by comma should be auto-completed.
2) How can we manage that special signs (for example e,é or a,ä) will be case-insensitive, so when typing in Andre, beside Andre also André will be matched.

Thanks for your work!

**Comment by SimonSteinberger** [comment]
Hi opiekuni,

that's actually both purely a task for your server. The script sends the users input to your server and you'll need to guess, whether it's a bout a city, a country or a state. The same goes for case-sensitivity. That's something you can decide and implement independently from the jQuery plugin.
