### ISSUE TITLE
Vertical scroll bar disappears

### ISSUE THREAD

**Issue by currygoat11** [Pixabay/jQuery-autoComplete#12]
I downloaded and have trying out this control. Version 1.0.5.

The problem I'm having is that when Internet Explorer (I'm running version 11), when I type "a" for example and a large list appears in the drop down (and a vertical scroll bar appears), when I move the mouse to the vertical scroll bar and click on the bar to try to slide the bar down using the mouse, the drop down immediately disappears. This behavior does not happen in Chrome. This is easily reproduceable (http://goodies.pixabay.com/jquery/auto-complete/demo.html). Please can this be addressed?

**Comment by SimonSteinberger** [comment]
Fixed.
