### ISSUE TITLE
Support for focus

### ISSUE THREAD

**Issue by svanegaard** [Pixabay/jQuery-autoComplete#14]
Would it be possible to make the autocomplete fire on the input focus event? It could just be an option in the params list when initialising the autocomplete.

Also, thank you for a great minimal pluginl

**Comment by SimonSteinberger** [comment]
I've put it on my to-do list. I think that shouldn't be too hard to implement, just lacking the time right now. If you have a code fragment to include for it, just post it here or create a pull request :-)

**Comment by edgardluz** [comment]
that.on('focusin', function(){ if (o.minChars === 0) that.val('').trigger("keyup.autocomplete"); })

That's all you need... basically if you set minChars: 0 it will trigger the autocomplete menu when you focus on the input... I also have a blur that sets the previous value back if no option was chosen... 

By the way, i love this little plugin and have heavily modified it to do a bunch of stuff I need. Thanks for the hard work!

**Comment by SimonSteinberger** [comment]
Nice! Thanks edgardluz :+1: I'll include a slightly modified LOC in a few minutes.

that.on('focus.autocomplete', function(){ if (!o.minChars) { that.last_val = '\n'; that.trigger('keyup.autocomplete'); } });

I've renamed the event, so it'll get detached when the destroy method is used. I couldn't find out why you're using the focusin event (vs. focus). It all seem to work with focus so far.

Let me know please, when there are any issues with this feature.

**Comment by svanegaard** [comment]
That was fast :wink:

I got it working myself pretty fast, but anyways :thumbsup:

**Comment by edgardluz** [comment]
i have other events attached to "focus" to other events... so i didn't want
them to stop working when i destroyed the autocomplete from them. that's
why i used focusin instead. but i see you used focus.autocomplete... so
that might be better anyway.
