### ISSUE TITLE
Search from the beginning of string

### ISSUE THREAD

**Issue by MonrealRyan** [Pixabay/jQuery-autoComplete#15]
Hi, 
Can i ask if it is possible to search an item from the beginning of the string only?
Like [this](http://www.jensbits.com/2011/04/28/jquery-ui-autocomplete-search-from-beginning-of-string/).

Thanks.

**Comment by SimonSteinberger** [comment]
That's up to you. Your source function can evaluate the incoming term and return data that matches only the beginning of a string.

**Comment by MonrealRyan** [comment]
got it. Thank you
