### ISSUE TITLE
second request after selecting an item

### ISSUE THREAD

**Issue by ak04nv** [Pixabay/jQuery-autoComplete#17]
I use $.getJSON for get suggestions without cache.
When I select an item by mouse click everything is ok, but if I press a `Enter` on keyboard browser makes a second ajax-request. Adding a '13' code in list on [this line](https://github.com/Pixabay/jQuery-autoComplete/blob/master/jquery.auto-complete.js#L130) fix this issue for me.
```javascript
if (!~$.inArray(e.which, [13, 27, 38, 40, 37, 39])) {
```

**Comment by SimonSteinberger** [comment]
I'm afraid I can't say much about this issue without actually seeing the code or a working JSFiddle. So, I'm not sure if it's a bug in the plugin or the implementation.

**Comment by ak04nv** [comment]
Try in this [example](https://jsfiddle.net/ku8787nz/) type one letter and select any suggestion by keyboard (arrows and enter).

**Comment by SimonSteinberger** [comment]
Thanks, that was a good catch!
