### ISSUE TITLE
AJAX call

### ISSUE THREAD

**Issue by TheTouristDev** [Pixabay/jQuery-autoComplete#22]
When i make an AJAX call all the results are shown?

Is there any problem?

json ["bike","carro"]

    $().ready(function() {
        var xhr;
          $('#equipa').autoComplete({
              source: function(term, response){
                  try { xhr.abort(); } catch(e){}
                  xhr = $.getJSON('includes/autocomplete.php', { q: term }, function(data){ response(data); });
              }

          });
            });

**Comment by SimonSteinberger** [comment]
The plugin shows what is returned b your source function. Actually, I don't see the point of your question/issue.
