### ISSUE TITLE
Errors and caching

### ISSUE THREAD

**Issue by nunocastromartins** [Pixabay/jQuery-autoComplete#23]
Hello!

On your demo page you state that, when specifying the `source` function, its `response` callback must always be called, even in the event of an error.
In my case (and I believe this to be a regular use-case), my `source` function performs an AJAX request on some server. Servers may, sometimes, respond with an error (e.g. the server is overloaded), even if my query is correct.
However, since I have caching enabled, the plugin will cache the value I pass to the `response` callback - and remember than an unexpected error occurred, so I don't have a proper value to pass. This is troublesome: if I retype the previous query, it won't reattempt to fetch proper suggestions.

So, what value should I pass to the `response` function on the event of an error? From looking at the source code you cache whatever value is passed (even if not an array).
If you agree that this is indeed an issue, an easy way to fix it would be to check if the value passed is an array, and only then cache it. This would mean that, on the event of an error, I could call the response callback with no arguments and nothing would be cached.
Another suggestion would be to expect two callback functions in the `source` function, the second for dealing with errors (and one should always be called).

Anyway, thank you for the very useful plugin!

**Comment by SimonSteinberger** [comment]
Oh, you're right. It should be fairly simple to handle this ... I'll take a look at it soon. Thanks!

**Comment by nunocastromartins** [comment]
If you're interested, I simply changed your `suggest` function to:
```
function suggest(data){
    var val = that.val();
    if (Object.prototype.toString.call(data) === '[object Array]' && data.length && val.length >= o.minChars) {
        that.cache[val] = data;
        var s = '';
        for (var i=0;i<data.length;i++) s += o.renderItem(data[i], val);
        that.sc.html(s);
        that.updateSC(0);
    }
    else
        that.sc.hide();
}
```
(Only cache if the received argument is an array)

**Comment by nunocastromartins** [comment]
Oops, that is wrong, you should also cache when the array is empty. Well, it's really simple, anyway.

**Comment by SimonSteinberger** [comment]
Sure, got it :+1:

**Comment by SimonSteinberger** [comment]
Or possibly start the function with:

    if (data === false) return;

**Comment by nunocastromartins** [comment]
So I have to call the `response` callback with `false`?
Sure, I don't mind! Anything is fine, really. :)

**Comment by SimonSteinberger** [comment]
"if (!data) return;" includes an empty array, so that's probably not ideal.

**Comment by nunocastromartins** [comment]
An empty array is an object, it is still a truthy value.
It would include the number `0`, but that shouldn't be an issue.

**Comment by SimonSteinberger** [comment]
Too much Python for me, recently :-D You're right. So yours is probably the best choice.

**Comment by nunocastromartins** [comment]
On a side note, by doing that `that.sc.hide();` won't run. I'm not sure if that is troublesome, you should know better. :)
By the way, I've got another "complaint", should I open another issue or just write here?
Well, I'll open another issue. Although I don't want to trouble you too much. ;)

**Comment by SimonSteinberger** [comment]
`that.sc.hide();` hides the suggestions in case no hits were found. At least that's what it's supposed to do. Can't see the problem there.

**Comment by nunocastromartins** [comment]
I assumed so, but on the event of an error shouldn't there be no suggestions?
I mean, if I had typed (using your demo page as an example) "Java", and then I type "S" and an error occurs. If you don't hide the window, both "Java" and "JavaScript" will show as suggestions. Even though "Java" shouldn't anymore. Also, both will only have the "Java" part in blue.

But hey, maybe it's better to keep them showing? I don't know, up to you. :)

**Comment by nunocastromartins** [comment]
These errors are rare, anyway. I only noticed the issue because it happened once. It's mostly solved with your suggestion, anyway. The non-caching part was most important.

**Comment by SimonSteinberger** [comment]
Doesn't really matter to me, either ... I guess I'd go for the most simple solution, because it's a rare scenario. At least it should be :-D

**Comment by SimonSteinberger** [comment]
I was just about to implement this, but realized: Isn't it simpler to just *not* call the callback inside your source function in case of an error. That should result in the same behavior as `if (!data) return;`. In that case, I'd simply adapt the documentation.

**Comment by nunocastromartins** [comment]
Of course it is simpler!
I only started this issue because the documentation specifically said to **always** call the callback function - even in the event of an error.
If you think it is okay not to call it, do that - just update the documentation. :)

**Comment by SimonSteinberger** [comment]
Perfect - I'll do so right away. The docs should state something like this: "You must call the callback, even if no hits are returned. Not calling it on error is fine."
