### ISSUE TITLE
Modifying autoComplete to work on enter and tab

### ISSUE THREAD

**Issue by alexandruradulescu** [Pixabay/jQuery-autoComplete#27]
Hi, 

When I am using the keyboard to select one of the items in the dropdown, if I press enter key it tries to submit the form.
How could I make it work also on enter (to override the default form behaviour)?

Cheers,
Alex

**Comment by SimonSteinberger** [comment]
For example, catch the enter event on the input field and `return false`; I beliebe there's no need for a change of the plugin code.

**Comment by landwire** [comment]
I personally think the enter behaviour is fine as it speeds things up on single input forms, but the tab behaviour is odd, as it completes the input field, when you choose and item with tab from the list, but it does not call onSelect. IMO either tab should not complete the input field or it should call onSelect.
