### ISSUE TITLE
provide example with suggestions for AJAX

### ISSUE THREAD

**Issue by nekromoff** [Pixabay/jQuery-autoComplete#30]
there is no example provided for AJAX and the example is not descriptive enough

source: function(term, suggest){
        try { xhr.abort(); } catch(e){}
        var suggestions = [];
        xhr = $.getJSON('randomsearch.php', { q: term }, function(data){ $('#searchquery').text(term); renderitems(data); });
    },

how should be suggestions vs choices and matches handled in this case? this is not explained properly as all the suggestion examples are only given for the static list of choices.

**Comment by SimonSteinberger** [comment]
`renderItem` and its use is explained in "Advanced suggestions handling and custom layout" - the example with the country names. All you have to do to make this work with Ajax, is replacing the static list of choices/suggestions with an Ajax call that returns a list of suggestions in the following format:
`var suggestions = [['Australia', 'au'], ['Austria', 'at']];`
After having received this array via Ajax, run the callback `suggest(suggestions);`.

**Comment by nekromoff** [comment]
then how does suggest know where to redirect user after selection is made?
there is no URL provided?

On Fri, Jul 31, 2015 at 11:14 AM, SimonSteinberger <notifications@github.com

**Comment by SimonSteinberger** [comment]
I don't understand what you mean. I don't see a connection between the autoComplete plugin and redirects/URLs.

**Comment by abhishek321** [comment]
$('#Subject_Name').autoComplete({
    minChars: 2,
    source: function(term, response){
        term = term.toLowerCase();
        $.getJSON('/ajax', { q: term }, function(data){
            var suggestions = [];
                for (i=0;i<data.length;i++)
                    if (~data[i].toLowerCase().indexOf(term)) suggestions.push(data[i]);
                response(suggestions);
        });
    }
});
use this
