### ISSUE TITLE
we need to escape special characters in input

### ISSUE THREAD

**Issue by LexRiver** [Pixabay/jQuery-autoComplete#34]
if input contains special characters like parentheses then some exceptions occurs.
we can use solution from here: 
http://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex

**Comment by SimonSteinberger** [comment]
I guess that depends on the `renderItem` function. If I see that right, it's not something that needs to be handled inside the plugin, does it?

**Comment by LexRiver** [comment]
If you add some value to suggestion, like "value (value)", than some exceptions occurs.
If we escape chars in render function, then it's ok:
```javascript
        renderItem: function (item, search){
            //escape special characters
            search = search.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
            var re = new RegExp("(" + search.split(' ').join('|') + ")", "gi");
            return '<div class="autocomplete-suggestion" data-val="' + item + '">' + item.replace(re, "<b>$1</b>") + '</div>';
        },
```

**Comment by SimonSteinberger** [comment]
Thanks Lex! I've just included a slightly modified patch based on this:
http://stackoverflow.com/questions/3561493/is-there-a-regexp-escape-function-in-javascript

It's essentially exactly your solution, just with a few bytes shorter Regex. No need to escape all characters inside the brackets [...].
