### ISSUE TITLE
Create release for v1.0.7

### ISSUE THREAD

**Issue by u01jmg3** [Pixabay/jQuery-autoComplete#38]
Can you create a release for `v1.0.7` so I can download this version with bower?

**Comment by quinncomendant** [comment]
Yes please. I just notice the bower version is serving v1.0.5.

**Comment by geloh** [comment]
First thanks for this great plugin. As noticed above bower is serving v1.0.5

**Comment by Hacktivista** [comment]
@SimonSteinberger Why this isn't fixed yet? please add release, I've lost some time trying to workaround some things :(

**Comment by SimonSteinberger** [comment]
The master code's Bower file states 1.0.7 as the current version. Bower should read the master version of a GitHub repo. If it doesn't, I'd say that's a Bower issue. If I could, I would actually remove all previous version tags, because there is no use for them in such a project.

**Comment by Hacktivista** [comment]
@SimonSteinberger 
You need to add the 1.0.7 tag:
`git tag -a 1.0.7 -m "Version 1.0.7 - 2015/08/15"`
`git push --tags`

But please don't delete previous tags :P

Thanks!

**Comment by Hacktivista** [comment]
@SimonSteinberger You are not able to do this?

**Comment by SimonSteinberger** [comment]
I am able to, but I won't create an extra tag repo just because Bower is incapable to read the current version.

**Comment by Hacktivista** [comment]
Not good, is simply how bower works. Maybe fix it on possible next release?

**Comment by SimonSteinberger** [comment]
The problem I'm actually having, is that with each GitHub tag, the whole repo get's copied onto my computer into an extra folder. And having quite a few GitHub projects that I'm working with, the whole thing is starting to get messy. Lots and lots of files and sub folders make the SVN folder on my hard drive blow up more and more. And that's annoying. But I'll take a look if there's a way to prevent having  local tag folder clones.

**Comment by SimonSteinberger** [comment]
Couldn't find a solution, yet. But found one to make  bower install an untagged version:
http://stackoverflow.com/questions/16949173/how-to-install-latest-untagged-state-of-a-repo-using-bower

**Comment by SimonSteinberger** [comment]
Version tag created.

**Comment by 3ynm** [comment]
Cheers!!
