### ISSUE TITLE
Passing an array as choices - how to get the value

### ISSUE THREAD

**Issue by landwire** [Pixabay/jQuery-autoComplete#39]
Hi there,
I am passing an array into choices as per your example with the countries and flags - just names and ids instead [['Sascha', 2], ['Klaus', 5]].

I use this to display, so names are displayed, ids are stored in data-id
return '<div class="autocomplete-suggestion" data-id="' + item[1] + '" data-val="' + item[0] + '">' + item[0].replace(re, "<b>$1</b>") + '</div>';

Which works great. BUT: how do I access the id value in data-id on form submission? It is not passed to the original targeted input element as far as I can see or is it?

**Comment by SimonSteinberger** [comment]
You can access the element inside the onSelect callback.

**Comment by landwire** [comment]
Thanks for the quick reply! I tried to assign a value with .data(), which obviously did not work .attr did the trick: $target.attr( 'data-id', jQuery(item[0]).data('id') ); My bad!

Now I was wondering if it would make sense to have an onDeselect option/callback.
Use case:
1. user chooses item -> id get's populated with $target.attr( 'data-id', jQuery(item[0]).data('id') );
2. user decides to empty the field again and type his own text (not an autocomplete term!)
3. then the data-id value does not get updated but stays at the value chosen at 1.

Or is there a different way to solve that?

**Comment by SimonSteinberger** [comment]
You could probably use the onChange event of the input field to unset the data attribute.

**Comment by landwire** [comment]
Just tried and that works fine. Thanks again!
