### ISSUE TITLE
ajax sending redundant

### ISSUE THREAD

**Issue by amir-hz** [Pixabay/jQuery-autoComplete#41]
when I had to choose one result, then I delete all text and start typing again, sending ajax become redundant

ps: sorry for my bad english

![error1](https://cloud.githubusercontent.com/assets/7609160/10935707/659df46a-831a-11e5-8d34-8cc2af0b7a11.jpg)

**Comment by SimonSteinberger** [comment]
I'm not completely understanding the issue. Could you explain with some more details on how to reproduce this? With caching enabled, no redundant requests should be sent, so this is definitely an important bug report! Thanks.
