### ISSUE TITLE
How I can get the ID or Data attr of input?

### ISSUE THREAD

**Issue by nunoguerra** [Pixabay/jQuery-autoComplete#45]
Hi!

Thanks for the good work to made this plugin it is awesome.

But I have some problem, the data is saved when input change, and I need to get the ID of input to do change event.

How I can get the ID or Data attr of input?

I need get the element of input here:

onSelect: function(e, term, item){
        $(some_ref_of_element).val(term).change();
}

**Comment by SimonSteinberger** [comment]
I believe, the second example on the demo page shows exactly how this is accomplished:
https://goodies.pixabay.com/jquery/auto-complete/demo.html
Look for:
"Advanced suggestions handling and custom layout"

**Comment by nunoguerra** [comment]
Hi Simon

How I can get the reference of input element in this example?

I need something like this:

onSelect: function(e, term, item){
$(some_ref_of_element).val(term).change();
}

Thanks for help.

Cheers.

**Comment by amnwebmaster** [comment]
this would be very handy

**Comment by designosis** [comment]
Yes please :) There doesn't seem to be any reference to the originating input element, which forces me to hardcode `#ids`, limiting my options a bit.

**Comment by eudard** [comment]
You need to change file **jquery.auto-complete.js** source code at line 146 in  

change this..
`that.timer = setTimeout(function(){ o.source(val, suggest) }, o.delay);`
to this
`that.timer = setTimeout(function(){ o.source(val, suggest, that) }, o.delay);`

and code example is..

$(".autocomplete-ajax").autoComplete({
   source: function(term, response, **item**){
      url = **item.attr('data-url');**
       $.getJSON(url, { q: term }, function(data){ response(data); });
 }
});

**Comment by oshihirii** [comment]
I am also looking for reference to `$(this)` ie the input where the autocomplete is applied.  

The only related information I can find is:

> onSelect(event, term, item) | A callback function that fires when a suggestion is selected by mouse click, enter, or tab. event is the event that triggered the callback, term is the selected value. and item is the item rendered by the renderItem function.

But when I `console.log()` either `event` or `term` or `item`, there don't seem to be any references to the instance where autocomplete is applied.

**Comment by oshihirii** [comment]
Just figured out a "hacky" way to do this, on the `onSelect` callback find the index of the suggestions container div:
```js
var instance = $(event.target).closest(".autocomplete-suggestions").index(".autocomplete-suggestions");
```
Then use it to target the relevant input instance, eg:
```js
$(".my_input").eq(instance)
```
It is a pity:

- There isn't a `$(this)` like reference for the instance
- That you have to add data attributes to each suggestion in order to later use the values, rather than just being able to pass them through all the callbacks used (ie `item.my_great_key_value` does not persist throughout the callbacks, you have to add it to a suggestion with `renderItem` and then call it with `item.data("my_great_key_value")`).  Seems like it is adding lots of HTML to the page?

**Comment by oshihirii** [comment]
FYI, for those looking, the [devbridge autocomplete plugin](https://github.com/devbridge/jQuery-Autocomplete) passes the item through to the onSelect handler by default, I have put together heavily commented [codepen demo here](https://codepen.io/oshihirii/full/EvMjZm).
