### ISSUE TITLE
in firefox Chinese input method not work

### ISSUE THREAD

**Issue by yumin5723** [Pixabay/jQuery-autoComplete#48]
i use Chinese input method in firefox ,but not work,unless i delete a word. what should i fix?

**Comment by SimonSteinberger** [comment]
Not having a Chinese OS or keyboard, I cannot reproduce the issue here. If you find a solution, please post it, so we can include it in the code base.

**Comment by kevinevil** [comment]
My FireFox is OK ,You can set minChars: 1 to try.
