### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by adam-lynch** [Pixabay/jQuery-autoComplete#5]
Would be handy :+1:

**Comment by SimonSteinberger** [comment]
I can create and provide the bower.js file. But someone else needs to register the package with bower. I'm on a Windows machine and I'm not sure if there's a working solution for registering bower apps without Linux.

**Comment by adam-lynch** [comment]
I'm pretty sure you can because I'm on Windows most of the time and I've registered packages in the past (so I think I probably did on Windows).

**Comment by SimonSteinberger** [comment]
I've just uploaded the bower.js file. I should be able to register the app by tomorrow.
