### ISSUE TITLE
About the latest version

### ISSUE THREAD

**Issue by x09326** [Pixabay/jQuery-autoComplete#56]
Hi, I'm going to host this lib on [https://cdnjs.com](url).
But I meet a problem.
Because I need to add the git autoupdate config.
Can you add the latest version tag?

I saw the version of the `master` branch is 1.0.7.
But your latest version tag is still 1.0.5.

https://github.com/cdnjs/cdnjs/issues/7572

**Comment by SrijanBajracharya** [comment]
@SimonSteinberger @skttl 
please update the version tag

**Comment by SimonSteinberger** [comment]
Version tag created.

**Comment by x09326** [comment]
Thank you for your help.
I will send a pull request to cdnjs recently.
