### ISSUE TITLE
onSelect should return the suggestion item

### ISSUE THREAD

**Issue by adam-lynch** [Pixabay/jQuery-autoComplete#7]
1. I use the `source` function to provide an array of objects. Great.
2. I use `renderItem` to take each one of these objects and generate some HTML from them. Great.
3. I select one of the suggestions. The field's text is passed to `onSelect`. Bad.
4. I noticed the `data-val` attribute is what is actually passed to `onSelect`. I change this to contain an ID so in `onSelect` I can then look up this ID and get the associated object. Not nice since it still doesn't give me the actually item / object when I select but it'll do as a workaround. Nope, when I press `down` to go onto an item, the ID is shown in the field. So whatever `data-val` is, that's what's shown in the field but there's no way of accessing the source data. Bad.

Preferably, `onSelect` should be passed the item (too).

**Comment by adam-lynch** [comment]
To be clear, this is especially a problem because the text to displayed in the field may not be unique. Think of a list of people where two people may have the same name.

**Comment by SimonSteinberger** [comment]
Oops, sorry for getting back to you so late! Somehow I lost sight of the issue and totally forgot about it. I've put it on our to-do list, because I think it would be great to have a solution for it.

**Comment by SimonSteinberger** [comment]
I looked into this, but I keep running into issues. I'm not sure if this plugin is really made for this functionality. It's currently an autocompleter that - as the name suggests - simply tries to complete some input text.

However, what you're looking for is actually an auto-suggester. Just as an example to show the difference, here's an auto-suggester:
http://jqapi.com/
Try searching for "fade". You'll get a handful of suggestions, but the input field is not filled with these choices while hovering the suggestions. Even when pressing enter, the input field remains unchanged.

The whole thing looks very similar, but when looking closer into the workflow behind the scenes, these are very different things. I'd like to combine both here, but I couldn't come up with a smart solution so far.

**Comment by SimonSteinberger** [comment]
Just took a closer look at your pull requests - somehow I must have missed them, too. Maybe I had some email issues at the time. Anyways, I think that's a good workaround, although not completely the same as a real auto-suggester. I'll include this right away in the plugin. Thanks for your work!

**Comment by adam-lynch** [comment]
No bother

**Comment by SimonSteinberger** [comment]
Ok, I've just included your pull requests with minor modifications (passing the event to the onSelect callback to determine whether enter key or mouse triggered it). Please let me know if you encounter any problems.

**Comment by SimonSteinberger** [comment]
I've just included a thorough example for this rather complex use case on the demo page:
http://goodies.pixabay.com/jquery/auto-complete/demo.html

**Comment by oshihirii** [comment]
I would like pressing `Enter` on a suggestion to cause the same behaviour as clicking on a suggestion.  

It seems the `onSelect` event can determine if the `Enter` key was pressed, but will not act the same as when clicking on a suggestion, even when this is specifically defined:
```js
onSelect: function(e, term, item){

function doit() {

console.log("doit() is running..."); 

// get instance of input
var instance = $(e.target).closest(".autocomplete-suggestions").index(".autocomplete-suggestions");
  
// get refererence to relevant elements
var $product_desc = $(".product_desc").eq(instance);
var $product_type = $(".product_type").eq(instance);
var $product_attr_01 = $(".product_attr_01").eq(instance);
var $product_attr_02 = $(".product_attr_02").eq(instance);

// populate fields with relevant data
$product_desc.val(item.data("product_desc"));
$product_type.val(item.data("product_type"));
$product_attr_01.val(item.data("product_attr_01"));
$product_attr_02.val(item.data("product_attr_02"));
}
  
if (e.type === "keydown") {
console.log("the keydown event was captured");
doit();
}
else {
console.log("the keydown event was not captured");
doit(); 
}

}
```
In this example, when keydown is detected, the population of fields does not occur.

**Comment by oshihirii** [comment]
FYI, for those looking, the [devbridge autocomplete plugin](https://github.com/devbridge/jQuery-Autocomplete) passes the item through to the onSelect handler by default, I have put together heavily commented [codepen demo here](https://codepen.io/oshihirii/full/EvMjZm).
